branches:
  only:
    - master
language: node_js
node_js:
  - 12.7.0
before_script:
  - npm install @11ty/eleventy -g
script: eleventy --pathprefix="/mason-motorsports-facts/"
deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
